[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=1MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[program:setup]
directory=/tmp
command=/app/setup.sh
startretries=0

[program:redis1]
directory=/tmp
command=redis-server /app/redis1.conf

[program:redis2]
directory=/tmp
command=redis-server /app/redis2.conf

[program:redis3]
directory=/tmp
command=redis-server /app/redis3.conf

[program:redis4]
directory=/tmp
command=redis-server /app/redis4.conf

[program:redis5]
directory=/tmp
command=redis-server /app/redis5.conf

[program:redis6]
directory=/tmp
command=redis-server /app/redis6.conf
